/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

(* top =  1  *)
(* src = "mult_8.v:1.1-3.10" *)
module mult8(a, y);
  (* src = "mult_8.v:1.27-1.28" *)
  input [2:0] a;
  wire [2:0] a;
  (* src = "mult_8.v:1.44-1.45" *)
  output [5:0] y;
  wire [5:0] y;
  assign y = a * (* src = "mult_8.v:2.13-2.18" *) 4'h9;
endmodule
