/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

(* top =  1  *)
(* src = "mult_2.v:1.1-3.10" *)
module mul2(a, y);
  (* src = "mult_2.v:1.26-1.27" *)
  input [2:0] a;
  wire [2:0] a;
  (* src = "mult_2.v:1.42-1.43" *)
  output [3:0] y;
  wire [3:0] y;
  assign y = { a, 1'h0 };
endmodule
